//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RushHourEma.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RushHourEma.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP_DEFINITION_START
        ///name=ChillaxSS
        ///size=10
        ///exit=3
        ///cars=15,1,2,0;13,3,1,1;67,2,1,0
        ///MAP_DEFINITION_END.
        /// </summary>
        public static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP_DEFINITION_START
        ///name=ChillaxSS
        ///size=10
        ///exit=3
        ///cars=13,1,2,0;43,2,1,1;67,2,1,0
        ///MAP_DEFINITION_END.
        /// </summary>
        public static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP_DEFINITION_START
        ///name=ChillaxSS
        ///size=10
        ///exit=3
        ///cars=13,1,2,0;43,2,1,1;67,2,1,0
        ///MAP_DEFINITION_END.
        /// </summary>
        public static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap asphalt {
            get {
                object obj = ResourceManager.GetObject("asphalt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap box {
            get {
                object obj = ResourceManager.GetObject("box", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap horizontalcar {
            get {
                object obj = ResourceManager.GetObject("horizontalcar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream horn {
            get {
                return ResourceManager.GetStream("horn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP_DEFINITION_START
        ///name=ChillaxSS
        ///size=8
        ///exit=24
        ///cars=9,1,2,0;17,2,1,0;18,2,1,0;41,1,2,0;12,2,1,0;27,1,2,1;35,2,1,0
        ///MAP_DEFINITION_END.
        /// </summary>
        public static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP_DEFINITION_START
        ///name=Level 2
        ///size=8
        ///exit=8
        ///cars=9,2,1,0;10,3,1,0;11,3,1,0;25,3,1,0;34,2,1,0;49,1,3,0;35,1,3,0;13,1,2,1;21,1,2,0;38,3,1,0
        ///MAP_DEFINITION_END.
        /// </summary>
        public static string level2 {
            get {
                return ResourceManager.GetString("level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap policehorizontal {
            get {
                object obj = ResourceManager.GetObject("policehorizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap policetruckhorizontal {
            get {
                object obj = ResourceManager.GetObject("policetruckhorizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap policetruckvertical {
            get {
                object obj = ResourceManager.GetObject("policetruckvertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap policevertical {
            get {
                object obj = ResourceManager.GetObject("policevertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream trafficjamsound {
            get {
                return ResourceManager.GetStream("trafficjamsound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap truckhorizontal {
            get {
                object obj = ResourceManager.GetObject("truckhorizontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap truckvertical {
            get {
                object obj = ResourceManager.GetObject("truckvertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap verticalcar {
            get {
                object obj = ResourceManager.GetObject("verticalcar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
